# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-10 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='abonado',
            fields=[
                ('cedula', models.CharField(blank=True, max_length=10, null=True)),
                ('num_abonado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_abo1', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_abo2', models.CharField(max_length=30)),
                ('apellido_abo1', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido_abo2', models.CharField(max_length=30)),
                ('direccion_abo', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
