# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-10 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonado', '0001_initial'),
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula2', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_abo_serv1', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_abo_serv2', models.CharField(max_length=30)),
                ('apellido_abo_serv1', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido_abo_serv2', models.CharField(max_length=30)),
                ('direccion_abo_serv', models.TextField(blank=True, max_length=500, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('num_abonado3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonado.abonado')),
                ('serial2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.caja')),
            ],
        ),
    ]
