# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-10 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('num_abonado2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonado.abonado')),
            ],
        ),
    ]
